#!/usr/bin/env python3
L=[-17.5,"kilo",49,"V",["ram",5,"echo"],7]
print("L[0]={} L[-6]={}".format(L[0],L[-6]))
print("L[1]={} L[-5]={}".format(L[1],L[-5]))
print("L[1][0]={} L[-5][0]={}".format(L[1][0],L[-5][0]))
print("L[4][2]={} L[4][-1]={} L[-2][2]={} L[-2][-1]={}".format(L[4][2],L[4][-1],L[-2][2],L[-2][-1]))
